[workspace]
authors = ["zsk4 <zachary_katz@mines.edu>"]
channels = ["conda-forge"]
name = "david_radar"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
gdal = ">=3.11.3,<4"
segyio = ">=1.9.12,<2"
ipykernel = ">=6.30.1,<7"
h5py = ">=3.14.0,<4"

[pypi-dependencies]
impdar = ">=1.2.1, <2"
